**1.Write a Python Program to Add Two Matrices?**

In [3]:
m1 = [[1,2,3],[4,5,6],[7,8,9]]
m2 = [[1,2,3],[4,5,6],[7,8,9]]

result = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(m1)): #rows
    for j in range(len(m2)): #columns
        result[i][j] = m1[i][j] + m2[i][j]
        
print(result)

[[2, 4, 6], [8, 10, 12], [14, 16, 18]]


In [5]:
#using numpy

import numpy as np
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(m1+m2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


**2.Write a Python Program to Multiply Two Matrices?**

In [6]:
m1 = [[1,2,3],[4,5,6],[7,8,9]]
m2 = [[1,2,3],[4,5,6],[7,8,9]]

result = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(m1)): #rows
    for j in range(len(m2)): #columns
        result[i][j] = m1[i][j] * m2[i][j]
        
print(result)

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]


In [10]:
#using numpy

import numpy as np
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(m1*m2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


**3.Write a Python Program to Transpose a Matrix**

In [17]:
m1 = [[1,2,3],[4,5,6]]

result = [[0,0],[0,0], [0,0]]

for i in range(len(m1)): #rows
    for j in range(len(m1[0])): #columns
        result[j][i] = m1[i][j]        
print(result)

[[1, 4], [2, 5], [3, 6]]


In [20]:
#using numpy

import numpy as np
m1 = np.array([[1,2,3],[4,5,6]])

np.transpose(m1)

array([[1, 4],
       [2, 5],
       [3, 6]])

**4.Write a Python Program to Sort Words in Alphabetic Order?**

In [38]:
s = "Need to sort the words from this string in an alphabetic order."
l = s.title().split() # if title is not used then Capital letter takes precedence on lower letter
l.sort()
print(l)

['Alphabetic', 'An', 'From', 'In', 'Need', 'Order.', 'Sort', 'String', 'The', 'This', 'To', 'Words']


**5.Write a Python Program to Remove Punctuation From a String**

In [39]:
import string
s = 'abcd#$1~^%@11sdas'

for character in string.punctuation:
    s = s.replace(character, '')

print(s)

abcd111sdas
